# Doc infrastructure generated over the Docker
version: "3.7"

services:
  docusaurus:
    build:
      context: ./docker
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./:/app

