# Doc infrastructure generated over the Docker
version: "3.7"

services:
  # NodeJS
  node:
    image: node
    volumes:
      - ./:/app
    working_dir: /app/website

  # Server
  server:
    image: node
    ports:
      - 3000:3000
      - 35729:35729
    command: ["yarn", "start"]
    volumes:
      - ./:/app
    working_dir: /app/website

