# Doc infrastructure generated over the Docker
version: "3.7"

services:
  # Docusaurus
  docusaurus:
    image: node
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./website:/app

  # Deployer
  deployer:
    build:
      context: ./docker/deployer
      args:
        - PHP_VERSION=7
        - DEPLOYER_VERSION=latest
    env_file:
      - ./docker/deployer/deploy.env

    volumes:
      - ./deploy:/deploy
      - ./deploy/.ssh:/root/.ssh

